#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HypothesisTestingAndroid.Resource", IsApplication=true)]

namespace HypothesisTestingAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int font = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int calculateButtonImg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int headTitleText = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int htcIcon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int splashScreen = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int splashScreenCentre = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070003
			public const int blueDiv = 2131165187;
			
			// aapt resource value: 0x7f070011
			public const int calcButt = 2131165201;
			
			// aapt resource value: 0x7f07000b
			public const int editA = 2131165195;
			
			// aapt resource value: 0x7f070005
			public const int editN = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int editP = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int editR = 2131165193;
			
			// aapt resource value: 0x7f070010
			public const int imageView1 = 2131165200;
			
			// aapt resource value: 0x7f070001
			public const int linearLayout1 = 2131165185;
			
			// aapt resource value: 0x7f070013
			public const int p_XetX = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int p_XltORetX = 2131165204;
			
			// aapt resource value: 0x7f07000a
			public const int promptA = 2131165194;
			
			// aapt resource value: 0x7f070004
			public const int promptN = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int promptP = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int promptR = 2131165192;
			
			// aapt resource value: 0x7f07000d
			public const int radioOneTailed1 = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int radioOneTailed2 = 2131165198;
			
			// aapt resource value: 0x7f07000c
			public const int radioTailed = 2131165196;
			
			// aapt resource value: 0x7f07000f
			public const int radioTwoTailed = 2131165199;
			
			// aapt resource value: 0x7f070015
			public const int resetButt = 2131165205;
			
			// aapt resource value: 0x7f070000
			public const int scrollView1 = 2131165184;
			
			// aapt resource value: 0x7f070016
			public const int space2 = 2131165206;
			
			// aapt resource value: 0x7f070012
			public const int spaceAfterCalc = 2131165202;
			
			// aapt resource value: 0x7f070002
			public const int titleView = 2131165186;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Theme_Titanium = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int fonts = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] Fonts = new int[] {
					16842903,
					2130771968};
			
			// aapt resource value: 0
			public const int Fonts_android_textStyle = 0;
			
			// aapt resource value: 1
			public const int Fonts_font = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
